algo = input('digite algo: ')
print('o tipo primitivo desse valor é ', type(algo))
print('somente espaços ', algo.isspace())
print('é um numero ', algo.isnumeric())
print('é alfabetico', algo.isalpha())
print('tem letras e numeros ', algo.isalnum())
print('esta em maiusculas ', algo.isupper())
print('esta em minusculas ', algo.islower())
print('está capitalizada ', algo.istitle())